### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by tscorreia** [jMetal/jMetalPy#32]
Hi.
I get that output when I try to import the package: **from jmetal.algorithm import NSGAII** 

Traceback (most recent call last):
  File "Jmetal.py", line 1, in <module>
    from jmetal.algorithm import NSGAII
  File "/usr/lib/python2.7/site-packages/jmetalpy-0.5.1-py2.7.egg/jmetal/__init__.py", line 3, in <module>
    from jmetal import algorithm
  File "/usr/lib/python2.7/site-packages/jmetalpy-0.5.1-py2.7.egg/jmetal/algorithm/__init__.py", line 1, in <module>
    from .multiobjective.nsgaii import NSGAII
  File "/usr/lib/python2.7/site-packages/jmetalpy-0.5.1-py2.7.egg/jmetal/algorithm/multiobjective/nsgaii.py", line 24
    problem: Problem[S],
           ^
SyntaxError: invalid syntax

**Comment by ajnebro** [comment]
Hi.
  jMetalPy requires Python 3.6 or higher, and it seems that you are using Python 2.7.


Antonio

**Comment by tscorreia** [comment]
> Hi.
> jMetalPy requires Python 3.6 or higher, and it seems that you are using Python 2.7.
> 
> Antonio

Thank you so much. I didn't see that information on documentation.
It's working now. :)
